### ISSUE TITLE
Print success state

### ISSUE THREAD

**Issue by thd-fox** [artiebits/unix-print#12]
Is there a way to get feedback if file has been printed for real?

**Comment by abdullahTreesal** [comment]
same question here please help

**Comment by artiebits** [comment]
Hi guys! sorry for the late response. print function returns something like this `{ stdout: 'request id is myDummyPrinter-4 (1 file(s))' }`, where `myDummyPrinter` is my printer name, `myDummyPrinter-4` is my request id and `4` is the job id.
then you have 2 options:
* use `lpstat` to check if it contains your request id.
* use `lpq` to check if there is your job id in the queue.
You can add this functionality in your code, or, maybe someone is interested in contributing to this library

**Comment by artiebits** [comment]
the functionality has been implemented with this PR https://github.com/artiebits/unix-print/pull/13. please let me know if any issues
