### ISSUE TITLE
Print base64 files received by user

### ISSUE THREAD

**Issue by davimateus1** [artiebits/unix-print#30]
Good afternoon, I'm using your print-to-pdf library for Windows, and I want to know if there is any way to send a base64 instead of a path, the following example doesn't work, I can only print if I use the relative path from my computer (C://...)

Can you help me with this or can you point me to existing solutions, please?

Don't works:
![image](https://github.com/artiebits/unix-print/assets/66326378/a2a630c1-30ed-4940-8120-042e6fd8402c)

---

Works:
![image](https://github.com/artiebits/unix-print/assets/66326378/472df3b8-4cdb-4014-b6ad-6d040f647cbc)

**Comment by artiebits** [comment]
hi @davimateus1, pdf-to-printer is using SumatraPDF to print files. So, check if SumatraPDF allows this. If yes, then we could think of a solution.

**Comment by artiebits** [comment]
closing the issue for now. feel free to re-open it if you have more details or questions
