### ISSUE TITLE
lpstat -lp not working on MacOS Monterey

### ISSUE THREAD

**Issue by aashutoshrathi** [artiebits/unix-print#5]
Getting 
```
Error: Command failed: lpstat -lp
lpstat: No destinations added.
```

I think it should be `lpstat -l` here https://github.com/artiebits/unix-print/blob/d1a652a345afa66078e97548378456b1e1d04d39/src/get-printers/get-printers.ts#L7

**Comment by artiebits** [comment]
Hi @aashutoshrathi did you google `Error: Command failed: lpstat -lplpstat: No destinations added`? Looks like your system does not recognize local printer.

**Comment by aashutoshrathi** [comment]
Hey! @artiebits 
I don't have any printers added to my machine. (M1 Pro)
Is there a way to add dummy printers?

**Comment by artiebits** [comment]
that's why it's not working and `lpstat -l` will not work either. 

[How to add a dummy printer](https://gist.github.com/artiebits/85b306e331e0edd8abf84a544692379e)

**Comment by aashutoshrathi** [comment]
Thanks @artiebits
